### ISSUE TITLE
OTA update getting failed.

### ISSUE THREAD

**Issue by Raghav3107** [FreeRTOS/coreMQTT-Agent-Demos#52]
I was implemented the OTA using the coreMQTT-Agent library in a [custom repository](https://github.com/Raghav3107/amazon-freertos-workspace-v202012). When I m  trying to perform the OTA. It's getting failed. Can you help me with it?  why its getting failed? I have a very basic knowledge of the OTA code. I don't know how OTA is performing on the library side and its workflow. I will be very thankful if you explain the workflow of OTA.

![Ota-failed](https://user-images.githubusercontent.com/45571175/120110809-c0d99800-c18c-11eb-9c2b-bd05aacb0207.jpg)

**Comment by Yoimer** [comment]
@Raghav3107 Hi.

Have a look at this, https://www.freertos.org/2021/04/freertos-202104-00-includes-new-managed-ota-and-mqtt-capabilities-for-iot-applications.html.

It looks like you are using the `v202012` version of AWS FreeRTOS ESP32, and its `coreMQTT` library  and `OTA` can not be integrated that easy. I tried it in the past, and I got AWS reply here https://github.com/aws/amazon-freertos/issues/3056#issuecomment-818264611

I ended up using `v202007` which has `mqtt` (no `coreMQTT`) and it can be integrated with `ota`. So yes, you can push your data to AWS and at the same time have otas in your board.

**Comment by Raghav3107** [comment]
> I got AWS reply here [aws/amazon-freertos#3056 (comment)](https://github.com/aws/amazon-freertos/issues/3056#issuecomment-818264611)


@Yoimer in the comment they said we need to change the interface file `aws_iot_ota_mqtt.c` to adapt to new coreMQTT APIs. For that, they created the coreMQTT-Agent project. I think by using this lab_project OTA file  [ `ota_over_mqtt_demo.c` ]. We can perform the OTA on `v202012`
But as you can see I m facing some problem there. Let's wait for their reply. Maybe they can give us some valuable input.

**Comment by Yoimer** [comment]
> > I got AWS reply here [aws/amazon-freertos#3056 (comment)](https://github.com/aws/amazon-freertos/issues/3056#issuecomment-818264611)
> 
> @Yoimer in the comment they said we need to change the interface file `aws_iot_ota_mqtt.c` to adapt to new coreMQTT APIs. For that, they created the coreMQTT-Agent project. I think by using this lab_project OTA file [ `ota_over_mqtt_demo.c` ]. We can perform the OTA on `v202012`
> But as you can see I m facing some problem there. Let's wait for their reply. Maybe they can give us some valuable input.

@Raghav3107 Ok. Did you read this https://www.freertos.org/2021/04/freertos-202104-00-includes-new-managed-ota-and-mqtt-capabilities-for-iot-applications.html?

**Comment by pvyawaha** [comment]
Hello,

It seems you have some issues when opening the image state file. Can you confirm the place where you are executing the application can create the platform image state file. You can refer to windows simulator demo from https://github.com/FreeRTOS/FreeRTOS which has ota demo based on coreMQTT agent and the OTA LTS V3.

**Comment by Raghav3107** [comment]
> Can you confirm the place where you are executing the application can create the platform image state file.

I m executing on the Ubuntu OS. Here is my [custom aws repository. ](https://github.com/Raghav3107/amazon-freertos-workspace-v202012)


> You can refer to windows simulator demo from https://github.com/FreeRTOS/FreeRTOS which has ota demo based on coreMQTT agent

I m using the same ota_demo file of coreMQTT-Agent but not in the window simulator.

**Comment by pvyawaha** [comment]
Hello @Raghav3107,

Can you please confirm the PlatformImageState.txt is created when you run the demo and can you please try running it by first deleting PlatformImageState.txt created by previous terminated application?

**Comment by Raghav3107** [comment]
Hello @pvyawaha 

Can you tell me where I will check the PlatformImageState.txt is created or not? Can tell the directory where I  will search this file?

Regards,
Raghav

**Comment by pvyawaha** [comment]
@Raghav3107, it will be created in same place where you are executing the application. 

Code for it in your repository https://github.com/Raghav3107/amazon-freertos-workspace-v202012/blob/ad7710cb1c2c62bac88e98b03bf4482c0024b040/components/OTA/src/ota_pal.c#L471

**Comment by Raghav3107** [comment]
@pvyawaha, Okay I will test and update you about this.
Thanks for the reply.

**Comment by pvyawaha** [comment]
Hello @Raghav3107 ,

Are you still facing issue or this can be closed?

**Comment by Raghav3107** [comment]
Hello @pvyawaha,
Sorry for the late response.
I tested the OTA in the [repo](https://github.com/Raghav3107/amazon-freertos-workspace-v202012) and PlatformImageState.txt is not created on the repository.
