### ISSUE TITLE
Missing examples for Connect, Disconnect and Terminate APIs

### ISSUE THREAD

**Issue by boraozgen** [FreeRTOS/coreMQTT-Agent-Demos#61]
It would be helpful the include these APIs in the examples for better comprehension of the intended usage of them.

**Comment by ravibhagavandas** [comment]
Hi @boraozgen 

The reference examples provided, contains MQTT tasks that run continuously and  share a single connection using an MQTT agent task. It is a preferred approach for MQTT agent task itself to manage the connection in background by calling the coreMQTT connect and disconnect APIs directly as shown [here](https://github.com/FreeRTOS/coreMQTT-Agent-Demos/blob/c7456aab817b73d76d54f4d81d95e9a480ef014e/source/mqtt-agent-task.c#L515) . Hence specific usages of MQTT agent Connect and Disconnect APIs are not shown in this demo.
However, these APIs performs same operations as with coreMQTT Connect/Disconnect APIs, but using a queue under the hood for handling thread safety.

 For an example usage of MQTTAgent_Terminate API  you can refer the demo [here](https://github.com/aws/amazon-freertos/blob/f86418a59a640f2602aefd0d2b748c55bd437bf0/demos/coreMQTT_Agent/mqtt_agent_task.c#L998)

**Comment by boraozgen** [comment]
Thanks for the quick reply and explanation. IMHO the existence of these APIs is misleading and unnecessary if their usage is not shown in examples. Closing this issue as this is probably rather a discussion for the forums.
